import AppProvider from '@/modules/appContexts'
import ApolloProvider from '@/modules/apolloClient'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}><ApolloProvider><AppProvider>{children}</AppProvider></ApolloProvider></body>
    </html>
  )
}
